# Change these first
owner: technoogies # Your GitHub username
repo: upptime # Your Github repository name
assignees:
  - technoogies
# Add your sites here
sites:
  - name: Test Control (Goog)
    url: https://google.com
  - name: Technoogies
    url: https://technoogies.com
    maxResponseTime: 15000 #5000 = 5 sec.
    icon: https://technoogies.com/wp-content/uploads/2019/06/technoogies_Logo_Solid.png # Or favicon

  - name: Swet Inc
    url: https://www.swetinc.com/
    icon: https://www.swetinc.com/wp-content/uploads/design-assets/Swet_Logo_32x33_Rev.2a.png
    maxResponseTime: 15000 #5000 = 5 sec.
    expectedStatusCodes:
      - 200
#      - 201
#      - 404
#      - 503

  - name: It's For Africa!
    url: https://itsforafrica.org
    icon: https://itsforafrica.org/wp-content/uploads/design-components/icons/ifa-logo-no-bkgnd-no-fill-rev1d_50px.png
  - name: ComeOnAndFeedMe
    url: https://comeonandfeedme.com
    icon: https://comeonandfeedme.com/wp-content/uploads/assets/logo/coafm-logo-rev2c-5.png
  - name: It's Us Against Them!
    url: https://itsusagainstthem.com
    icon: https://itsusagainstthem.com/
    expectedStatusCodes:
      - 200
#      - 201
#      - 404
#      - 503
  - name: Tru Themes
    url: https://truthemes.com
    icon: https://truthemes.com/
    expectedStatusCodes:
      - 200
#      - 201
#      - 404
#      - 503
  - name: Oy 2 Us
    url: https://oy2.us/admin/
    icon: https://oy2.us/frontend/assets/img/Oy2Us_50px.png
    expectedStatusCodes:
      - 200
#      - 201
#      - 404
#      - 503
  - name: Tru Memes
    url: https://trumemes.com
    icon: https://trumemes.com/wp-content/uploads/branding/logo-media/tm-logo_social_rev1b50px.png
    expectedStatusCodes:
      - 200
  - name: Feasty Finds
    url: https://feastyfinds.com/
    icon: https://feastyfinds.com/wp-content/uploads/assets/logo/ff-logo-rev2b-tan-w-border_50px.png
    expectedStatusCodes:
      - 200
#      - 201
#      - 404
#      - 503

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.technoogies.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://technoogies.com/wp-content/uploads/header-items/technoogies.com-header-rev1c.png

  name: Upptime
  introTitle: "**Upptime** monitor and status page, powered entirely by GitHub."
  introMessage: This is an Uptime status page for [Technoogies.com](https://technoogies.com) which uses real-time data from here [Github repository](https://github.com/koj-co/upptime)   No server required — just GitHub Actions, Issues, Pages, and Open Source. [**Get your own for free**](https://github.com/koj-co/upptime)

  navbar:
    - title: Technoogies
      href: https://technoogies.com
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

  css: "body {
      background-image: linear-gradient(to bottom right, rgba(20, 255, 100, 0.1), rgba(20, 100, 255, 0.1);
    }"
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
