# Change these first
owner: technoogies # Your GitHub username
repo: upptime # Your Github repository name
assignees:
  - technoogies
# Add your sites here
sites:
  - name: Test Control
    url: https://google.com
  - name: Technoogies
    url: https://technoogies.com
    maxResponseTime: 15000 #5000 = 5 sec.
    icon: https://technoogies.com/favicon.ico
  - name: It's For Africa!
    url: https://itsforafrica.org
  - name: ComeOnAndFeedMe
    url: https://comeonandfeedme.com
  - name: Oy 2 Us
    url: https://oy2.us
  - name: TruMemes
    url: https://trumemes.com
  - name: Secret Site
    url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.technoogies.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://technoogies.com/wp-content/uploads/header-items/technoogies.com-header-rev1c.png
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is an Uptime status page for Technoogies which uses **real-time** data from here: [Github repository](https://github.com/koj-co/upptime)
No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
